### ISSUE TITLE
datetime inconsistency between set_rtc_alarm() and get_rtc_alarm().  

### ISSUE THREAD

**Issue by larrylisky** [tisboyo/pisugar2py#3]
The datetime value set using set_rtc_alarm() and the datetime read back using get_rtc_alarm() are not the same. The minute field is correct, but the hour field seems to be off by a number of hours.  It may be due to different timezone, but it's unclear what's happening from the code.  I basically wants the same functionality as 'set_test_wake' but with a programmable sleep time.  Any help/explanation would be appreciated.

**Comment by tisboyo** [comment]
It is undoubtedly a time zone issue, when you are setting the alarm time, does your datetime object include a timezone.

**Comment by larrylisky** [comment]
Yeah, I solved it.  The key is to figure out my time zone (-06:00) for US Central, and then edit this [part](https://github.com/tisboyo/pisugar2py/blob/master/__init__.py#L281) of your code to reflect it.  It might be good to make this a configuration parameter at the top of your code to raise awareness for this needed configuration.  Thanks for sharing this code.
